[package]
name = "pretty_tracing_subscriber"
version = "0.1.0"
authors = ["rd <cargo@megane.space>"]
edition = "2018"

[dependencies]
ansi_term = "0.12"
chrono = "0.4"
structopt = "0.3"
tracing = "0.1"
tracing-subscriber = "0.2"